apiVersion: v1
kind: ConfigMap
metadata:
  name: resilient-app-config
  namespace: resilient-demo
  labels:
    app.kubernetes.io/name: resilient-app
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: resilience-demo
data:
  # Application configuration
  APP_VERSION: "1.0.0"
  PORT: "8080"
  
  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "resilient_db"
  DB_USER: "postgres"
  
  # Resilience configuration
  GRACEFUL_SHUTDOWN_TIMEOUT: "30s"
  FEATURE_FLAGS: "graceful_degradation,circuit_breaker,metrics"
  CIRCUIT_BREAKER_THRESHOLD: "3"
  
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30s"
  READINESS_CHECK_TIMEOUT: "5s" 